### ISSUE TITLE
Building docker image via run_me.py fails

### ISSUE THREAD

**Issue by hansraj** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#8] opened 2021-05-05 07:21 UTC
INFO     CourseHandler        Welcome to 'Mastering Big Data Analytics with Pyspark' by Danny Meijer <chilltake@gmail.com>
INFO     CourseHandler        Course Version: 20200420
INFO     CourseHandler        Course Name: Mastering Big Data Analytics with Pyspark
INFO     CourseHandler        Container Name: mastering-pyspark-ml
INFO     CourseHandler        Downloading the data
INFO     CourseHandler        Processing Sentiment140TrainingData
INFO     CourseHandler        Directory "sentiment-140-training-data" already exists
INFO     CourseHandler        Skipping "trainingandtestdata.zip"
INFO     CourseHandler        Processing MovieLens-Small
INFO     CourseHandler        Directory "ml-latest-small" already exists
INFO     CourseHandler        Skipping "ml-latest-small.zip"
INFO     CourseHandler        Processing MovieLens
INFO     CourseHandler        Directory "ml-latest" already exists
INFO     CourseHandler        Skipping "ml-latest.zip"
INFO     CourseHandler        Connecting to Docker API
INFO     CourseHandler        Checking if Docker image is already set-up
WARNING  CourseHandler        Docker image has not been built yet
INFO     CourseHandler        Building Docker image
INFO     docker.api.build     Initiating (this might take a few moments)
Traceback (most recent call last):
  File "run_me.py", line 325, in <module>
    course = Course()
  File "run_me.py", line 117, in __init__
    self._image()
  File "run_me.py", line 256, in _image
    self.build_image()
  File "run_me.py", line 194, in build_image
    rm=True,
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\build.py", line 261, in build
    self._set_auth_headers(headers)
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\auth.py", line 302, in get_all_credentials
    for k in store.list().keys():
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\credentials\store.py", line 72, in list
    return json.loads(data.decode('utf-8'))
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Hansrajjadhav\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dannymeijer** [comment] 2021-05-05 07:36
What version of Docker is being used? I also would like to see the output
of `pip list`.
This might be down to an API change on Docker side - will have to
investigate this once I get the above information.

**Comment by hansraj** [comment] 2021-05-05 11:10
Package           Version
----------------- ---------
bitbucket-api     0.5.0
boto3             1.17.0
botocore          1.20.0
certifi           2020.6.20
chardet           3.0.4
Deprecated        1.2.10
docker            5.0.0
fake-useragent    0.1.11
gitdb             4.0.5
GitPython         3.1.11
idna              2.10
jmespath          0.10.0
numpy             1.19.2
oauthlib          3.1.0
pandas            1.1.2
pip               20.2.4
PyGithub          1.53
PyJWT             1.7.1
pyodbc            4.0.30
python-dateutil   2.8.1
pytz              2020.1
pywin32           227
requests          2.24.0
requests-futures  1.0.0
requests-oauthlib 1.3.0
s3transfer        0.3.4
setuptools        47.1.0
sh                1.14.0
six               1.15.0
smmap             3.0.4
urllib3           1.25.10
websocket-client  0.59.0
wrapt             1.12.1
xpressinsight     1.1.0

**Comment by hansraj** [comment] 2021-05-05 12:23
@dannymeijer 
You can take your time to check on it..
For the time being i have run the docker commands directly and modified the run_me.py to use the image created and spin up the container.

Thanks.

**Comment by dannymeijer** [comment] 2022-01-17 09:43
I never was able to get to the bottom of this one. It still works for me (even with latest version of Docker and Python) hence I am unable to reproduce the error.

Please let me know if you still need assistance.

**Comment by hansraj** [comment] 2022-01-17 11:30
Hi Danny -

Thanks for your response. Unfortunately I was not able to revert to your
earlier comment in May.

But it seemed like it was some intermittent issue due to the docker
version. Once I reinstalled it - it was working fine for me as well.

Regards,
Hansraj
--------------------------------------------------------------------------------------------------

**Comment by dannymeijer** [comment] 2022-01-17 11:57
Thanks @hansraj - closing this as requested

**Closed by dannymeijer** 2022-01-17 11:57 UTC
